"""EBU framework I-1: canonicalization, identity, hashing, and registries."""

from .canonical import (
    CanonicalBytes,
    CanonicalizationVersion,
    ECJ1Value,
    encode_ecj1,
    parse_ecj1,
)
from .errors import (
    DurabilityState,
    FailureCode,
    FailureEnvelope,
    PolicyMemoryAdvance,
    RetryClass,
    StateAdvance,
)
from .hashing import (
    compute_artifact_byte_hash,
    compute_augmented_replay_state_hash,
    compute_canonical_trace_payload_hash,
    compute_canonical_trace_prefix_hash,
    compute_canonical_trace_row_hash,
    compute_execution_semantics_hash,
    compute_information_view_hash,
    compute_object_content_hash,
    compute_policy_memory_payload_hash,
    compute_proposal_set_hash,
    compute_represented_state_projection_hash,
    compute_source_file_raw_sha256,
    compute_state_payload_hash,
)
from .identity import (
    ArtifactByteHash,
    AugmentedClosedLoopReplayStateHash,
    AuthorizationUseKey,
    CanonicalScientificTracePayloadHash,
    CanonicalTracePrefixHash,
    CanonicalTraceRowHash,
    ExecutionSemanticsHash,
    InformationViewHash,
    ObjectContentHash,
    ObjectRef,
    PolicyMemoryPayloadHash,
    ProposalSetHash,
    RepresentedStateProjectionHash,
    ScientificId,
    ScientificIdAllocationClaimV1,
    SemanticVersion,
    SourceFileRawSha256,
    StatePayloadHash,
    parse_scientific_id,
    parse_semantic_version,
)
from .registry import (
    AliasRecord,
    NamespaceEntry,
    NamespaceRegistrySnapshot,
    RegistryRecord,
    ResolutionRecord,
    allocate_scientific_id,
    register_draft,
    resolve_alias,
    resolve_ref,
)


__version__ = "0.1.0a1"

__all__ = (
    "AliasRecord",
    "ArtifactByteHash",
    "AugmentedClosedLoopReplayStateHash",
    "AuthorizationUseKey",
    "CanonicalBytes",
    "CanonicalScientificTracePayloadHash",
    "CanonicalTracePrefixHash",
    "CanonicalTraceRowHash",
    "CanonicalizationVersion",
    "DurabilityState",
    "ECJ1Value",
    "ExecutionSemanticsHash",
    "FailureCode",
    "FailureEnvelope",
    "InformationViewHash",
    "NamespaceEntry",
    "NamespaceRegistrySnapshot",
    "ObjectContentHash",
    "ObjectRef",
    "PolicyMemoryAdvance",
    "PolicyMemoryPayloadHash",
    "ProposalSetHash",
    "RegistryRecord",
    "RepresentedStateProjectionHash",
    "ResolutionRecord",
    "RetryClass",
    "ScientificId",
    "ScientificIdAllocationClaimV1",
    "SemanticVersion",
    "SourceFileRawSha256",
    "StateAdvance",
    "StatePayloadHash",
    "__version__",
    "allocate_scientific_id",
    "compute_artifact_byte_hash",
    "compute_augmented_replay_state_hash",
    "compute_canonical_trace_payload_hash",
    "compute_canonical_trace_prefix_hash",
    "compute_canonical_trace_row_hash",
    "compute_execution_semantics_hash",
    "compute_information_view_hash",
    "compute_object_content_hash",
    "compute_policy_memory_payload_hash",
    "compute_proposal_set_hash",
    "compute_represented_state_projection_hash",
    "compute_source_file_raw_sha256",
    "compute_state_payload_hash",
    "encode_ecj1",
    "parse_ecj1",
    "parse_scientific_id",
    "parse_semantic_version",
    "register_draft",
    "resolve_alias",
    "resolve_ref",
)
